services:
  # Backend API service
  paperless-dedupe:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: paperless-dedupe
    ports:
      - "30001:8000"
    environment:
      - PAPERLESS_DEDUPE_DATABASE_URL=sqlite:///app/data/paperless_dedupe.db
      - PAPERLESS_DEDUPE_SECRET_KEY=${SECRET_KEY:-change-me-in-production-use-a-long-random-string}
      # - PAPERLESS_DEDUPE_PAPERLESS_API_TOKEN=${PAPERLESS_API_TOKEN}
      # Or username/password auth
      # - PAPERLESS_DEDUPE_PAPERLESS_USERNAME=${PAPERLESS_USERNAME}
      # - PAPERLESS_DEDUPE_PAPERLESS_PASSWORD=${PAPERLESS_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache
    restart: unless-stopped

  # Frontend web UI service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: paperless-dedupe-frontend
    ports:
      - "30002:3000"
    depends_on:
      - paperless-dedupe
    restart: unless-stopped
