blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/rknightion/paperless-ngx-dedupe/discussions
    about: Please ask and answer questions in GitHub Discussions
  - name: Documentation
    url: https://github.com/rknightion/paperless-ngx-dedupe#readme
    about: Check the documentation for setup and usage information
  - name: Paperless-NGX Community
    url: https://github.com/paperless-ngx/paperless-ngx/discussions
    about: For paperless-ngx specific questions, visit the main project