/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/documents/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Documents
     * @description Get list of documents with cursor or offset pagination
     */
    get: operations['get_documents_api_v1_documents__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Document Stats
     * @description Get basic document processing statistics (legacy endpoint).
     */
    get: operations['get_document_stats_api_v1_documents_stats_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/statistics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Document Statistics
     * @description Get comprehensive document statistics including Paperless metadata
     */
    get: operations['get_document_statistics_api_v1_documents_statistics_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/{document_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Document
     * @description Get single document
     */
    get: operations['get_document_api_v1_documents__document_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/{document_id}/content': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Document Content
     * @description Get document OCR content
     */
    get: operations['get_document_content_api_v1_documents__document_id__content_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/{document_id}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Document Preview
     * @description Fetch a renderable preview from Paperless-NGX for hover/tooltips.
     */
    get: operations['get_document_preview_api_v1_documents__document_id__preview_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/{document_id}/duplicates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Document Duplicates
     * @description Get duplicates for a specific document
     */
    get: operations['get_document_duplicates_api_v1_documents__document_id__duplicates_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/sync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sync Documents
     * @description Sync documents from paperless-ngx using Celery task queue
     */
    post: operations['sync_documents_api_v1_documents_sync_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/statistics/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh Statistics
     * @description Manually refresh Paperless statistics cache
     */
    post: operations['refresh_statistics_api_v1_documents_statistics_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/sync/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Sync Status
     * @description Get current sync status
     */
    get: operations['get_sync_status_api_v1_documents_sync_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/duplicates/groups': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Duplicate Groups
     * @description Get list of duplicate groups with pagination and dynamic confidence recalculation
     */
    get: operations['get_duplicate_groups_api_v1_duplicates_groups_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/duplicates/groups/{group_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Duplicate Group
     * @description Get single duplicate group
     */
    get: operations['get_duplicate_group_api_v1_duplicates_groups__group_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Duplicate Group
     * @description Delete a duplicate group (marks as false positive)
     */
    delete: operations['delete_duplicate_group_api_v1_duplicates_groups__group_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/duplicates/groups/{group_id}/review': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark Group Reviewed
     * @description Mark a duplicate group as reviewed/resolved
     */
    post: operations['mark_group_reviewed_api_v1_duplicates_groups__group_id__review_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/duplicates/statistics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Duplicate Statistics
     * @description Get statistics about duplicates
     */
    get: operations['get_duplicate_statistics_api_v1_duplicates_statistics_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/processing/analyze': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Analysis
     * @description Start deduplication analysis using Celery task queue
     */
    post: operations['start_analysis_api_v1_processing_analyze_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/processing/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Processing Status
     * @description Get current processing status from Celery task
     */
    get: operations['get_processing_status_api_v1_processing_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/processing/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Processing
     * @description Cancel current processing
     */
    post: operations['cancel_processing_api_v1_processing_cancel_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/processing/clear-cache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear Cache
     * @description Clear cache endpoint (deprecated - no longer using cache)
     */
    post: operations['clear_cache_api_v1_processing_clear_cache_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/processing/internal/broadcast-task-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Broadcast Task Update
     * @description Internal endpoint for Celery workers to broadcast task updates via WebSocket
     */
    post: operations['broadcast_task_update_api_v1_processing_internal_broadcast_task_update_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/processing/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Processing History
     * @description Get processing history for recent runs
     */
    get: operations['get_processing_history_api_v1_processing_history_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/processing/cleanup-duplicates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cleanup Duplicate Data
     * @description Clean up all duplicate analysis data - useful for fixing corrupted state
     */
    post: operations['cleanup_duplicate_data_api_v1_processing_cleanup_duplicates_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ai/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Ai Jobs
     * @description List recent AI extraction jobs.
     */
    get: operations['list_ai_jobs_api_v1_ai_jobs_get'];
    put?: never;
    /**
     * Create Ai Job
     * @description Create a new AI extraction job and enqueue it.
     */
    post: operations['create_ai_job_api_v1_ai_jobs_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ai/jobs/{job_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Ai Job
     * @description Get a single AI extraction job.
     */
    get: operations['get_ai_job_api_v1_ai_jobs__job_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ai/jobs/{job_id}/results': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Ai Results
     * @description Return extracted results for a job.
     */
    get: operations['get_ai_results_api_v1_ai_jobs__job_id__results_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ai/jobs/{job_id}/apply': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apply Ai Results
     * @description Apply approved AI results to Paperless-ngx and local cache.
     */
    post: operations['apply_ai_results_api_v1_ai_jobs__job_id__apply_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ai/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check Openai Health
     * @description Validate OpenAI credentials/model once and store status.
     */
    get: operations['check_openai_health_api_v1_ai_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Config
     * @description Get current configuration
     */
    get: operations['get_config_api_v1_config__get'];
    /**
     * Update Config
     * @description Update configuration
     */
    put: operations['update_config_api_v1_config__put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config/defaults': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Config Defaults
     * @description Get default configuration from settings (no DB overrides).
     */
    get: operations['get_config_defaults_api_v1_config_defaults_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate Config
     * @description Validate configuration payload without saving.
     */
    post: operations['validate_config_api_v1_config_validate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config/test-connection': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Test Paperless Connection
     * @description Test connection to paperless-ngx API
     *
     *     Can test either:
     *     1. Provided configuration (without saving)
     *     2. Saved configuration from database
     *     3. Default configuration from settings
     */
    post: operations['test_paperless_connection_api_v1_config_test_connection_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset Config
     * @description Reset configuration to defaults
     */
    post: operations['reset_config_api_v1_config_reset_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batch/execute': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Execute Batch Operation Endpoint
     * @description Execute a batch operation on multiple documents or duplicate groups
     */
    post: operations['execute_batch_operation_endpoint_api_v1_batch_execute_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batch/status/{operation_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Operation Status
     * @description Get status of a batch operation
     */
    get: operations['get_operation_status_api_v1_batch_status__operation_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batch/documents/bulk-get': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Get Documents
     * @description Bulk fetch multiple documents by IDs
     */
    post: operations['bulk_get_documents_api_v1_batch_documents_bulk_get_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batch/documents/bulk-metadata-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Update Metadata
     * @description Bulk update metadata for multiple documents
     */
    post: operations['bulk_update_metadata_api_v1_batch_documents_bulk_metadata_update_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batch/operations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Operations
     * @description List recent batch operations
     */
    get: operations['list_operations_api_v1_batch_operations_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batch/cancel/{operation_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Cancel Operation
     * @description Cancel a pending or in-progress batch operation
     */
    delete: operations['cancel_operation_api_v1_batch_cancel__operation_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batch/duplicates/bulk-resolve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Resolve Duplicates
     * @description Bulk resolve duplicate groups by keeping primary document and deleting others
     */
    post: operations['bulk_resolve_duplicates_api_v1_batch_duplicates_bulk_resolve_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/batch/duplicates/bulk-review': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Review Duplicates
     * @description Bulk mark duplicate groups as reviewed/unreviewed
     */
    post: operations['bulk_review_duplicates_api_v1_batch_duplicates_bulk_review_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/internal/broadcast-task-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Broadcast Task Update
     * @description Receive task updates from workers and broadcast to WebSocket clients.
     *
     *     This endpoint is called by Celery workers to send progress updates
     *     to connected WebSocket clients.
     */
    post: operations['broadcast_task_update_api_v1_internal_broadcast_task_update_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get System Health
     * @description Get comprehensive system health status
     */
    get: operations['get_system_health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/quick': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Quick Health
     * @description Quick health check for uptime monitoring
     */
    get: operations['get_quick_health_api_v1_health_quick_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Health Metrics
     * @description Get detailed metrics for monitoring
     */
    get: operations['get_health_metrics_api_v1_health_metrics_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Api Root
     * @description API Root endpoint
     */
    get: operations['api_root_api_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Api Health
     * @description API Health check endpoint
     */
    get: operations['api_health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Health check endpoint for Docker
     */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AIHealthResponse */
    AIHealthResponse: {
      /** Healthy */
      healthy: boolean;
      /** Message */
      message?: string | null;
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
    };
    /** AIJobRequest */
    AIJobRequest: {
      /**
       * Tag
       * @description Existing Paperless tag name to select documents.
       */
      tag?: string | null;
      /**
       * Include All
       * @description Process all documents instead of filtering by tag.
       * @default false
       */
      include_all: boolean;
      /**
       * Target Fields
       * @description Fields to extract (title, correspondent, document_type, tags, date, all).
       */
      target_fields?: string[];
    };
    /** AIJobSummary */
    AIJobSummary: {
      /** Id */
      id: number;
      /** Status */
      status: string;
      /** Tag Filter */
      tag_filter?: string | null;
      /** Include All */
      include_all: boolean;
      /** Target Fields */
      target_fields: string[];
      /** Processed Count */
      processed_count: number;
      /** Total Count */
      total_count: number;
      /** Created At */
      created_at?: string | null;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
      /** Error */
      error?: string | null;
    };
    /** AnalyzeRequest */
    AnalyzeRequest: {
      /** Threshold */
      threshold?: number | null;
      /**
       * Force Rebuild
       * @default false
       */
      force_rebuild: boolean;
      /** Limit */
      limit?: number | null;
    };
    /** ApplyJobRequest */
    ApplyJobRequest: {
      /**
       * Result Ids
       * @description Optional list of result IDs to apply. Defaults to all pending results for the job.
       */
      result_ids?: number[] | null;
      /**
       * Fields
       * @description Optional subset of fields to apply. Defaults to the job's target fields.
       */
      fields?: string[] | null;
    };
    /** BatchOperationProgress */
    BatchOperationProgress: {
      /** Operation Id */
      operation_id: string;
      status: components['schemas']['OperationStatus'];
      /** Progress Percentage */
      progress_percentage: number;
      /** Current Item */
      current_item: number;
      /** Total Items */
      total_items: number;
      /** Message */
      message: string;
      /**
       * Errors
       * @default []
       */
      errors: string[];
      /** Results */
      results?: {
        [key: string]: unknown;
      } | null;
    };
    /** BatchOperationRequest */
    BatchOperationRequest: {
      operation: components['schemas']['OperationType'];
      /**
       * Document Ids
       * @description Document IDs to operate on
       */
      document_ids?: number[] | null;
      /**
       * Group Ids
       * @description Duplicate group IDs to operate on
       */
      group_ids?: string[] | null;
      /**
       * Parameters
       * @description Operation-specific parameters
       */
      parameters?: {
        [key: string]: unknown;
      } | null;
    };
    /** BatchOperationResponse */
    BatchOperationResponse: {
      /** Operation Id */
      operation_id: string;
      operation: components['schemas']['OperationType'];
      status: components['schemas']['OperationStatus'];
      /** Message */
      message: string;
      /** Total Items */
      total_items: number;
      /**
       * Processed Items
       * @default 0
       */
      processed_items: number;
      /**
       * Failed Items
       * @default 0
       */
      failed_items: number;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
    };
    /** Body_bulk_update_metadata_api_v1_batch_documents_bulk_metadata_update_post */
    Body_bulk_update_metadata_api_v1_batch_documents_bulk_metadata_update_post: {
      /** Document Ids */
      document_ids: number[];
      /** Updates */
      updates: {
        [key: string]: unknown;
      };
    };
    /** ComponentHealth */
    ComponentHealth: {
      /** Status */
      status: string;
      /** Latency Ms */
      latency_ms?: number | null;
      /** Details */
      details?: {
        [key: string]: unknown;
      } | null;
      /** Last Check */
      last_check?: string | null;
      /** Message */
      message?: string | null;
    };
    /** ConfigResponse */
    ConfigResponse: {
      /** Paperless Url */
      paperless_url?: string | null;
      /** Paperless Username */
      paperless_username?: string | null;
      /**
       * Paperless Api Configured
       * @default false
       */
      paperless_api_configured: boolean;
      /** Fuzzy Match Threshold */
      fuzzy_match_threshold: number;
      /** Max Ocr Length */
      max_ocr_length: number;
      /** Min Ocr Word Count */
      min_ocr_word_count: number;
      /** Lsh Threshold */
      lsh_threshold: number;
      /** Enable Fuzzy Matching */
      enable_fuzzy_matching: boolean;
      /** Fuzzy Match Sample Size */
      fuzzy_match_sample_size: number;
      /** Confidence Weight Jaccard */
      confidence_weight_jaccard: number;
      /** Confidence Weight Fuzzy */
      confidence_weight_fuzzy: number;
      /** Confidence Weight Metadata */
      confidence_weight_metadata: number;
      /** Confidence Weight Filename */
      confidence_weight_filename: number;
      /** Openai Model */
      openai_model?: string | null;
      /** Openai Reasoning Effort */
      openai_reasoning_effort?: string | null;
      /** Ai Max Input Chars */
      ai_max_input_chars: number;
      /**
       * Openai Configured
       * @default false
       */
      openai_configured: boolean;
      /** Openai Health Status */
      openai_health_status?: string | null;
      /** Openai Health Checked At */
      openai_health_checked_at?: string | null;
      /** Minhash Num Perm */
      minhash_num_perm: number;
      /** Lsh Num Bands */
      lsh_num_bands: number;
      /** Api Rate Limit */
      api_rate_limit: number;
      /** Api Page Size */
      api_page_size: number;
      /** Status */
      status?: string | null;
      /** Message */
      message?: string | null;
      /** Updated Fields */
      updated_fields?: string[] | null;
      /** Weights Changed */
      weights_changed?: boolean | null;
      /** Reanalysis Triggered */
      reanalysis_triggered?: boolean | null;
      /** Task Id */
      task_id?: string | null;
    };
    /** ConfigUpdate */
    ConfigUpdate: {
      /**
       * Paperless Url
       * @description Paperless-ngx API URL
       */
      paperless_url?: string | null;
      /**
       * Paperless Api Token
       * @description API Token for authentication
       */
      paperless_api_token?: string | null;
      /**
       * Paperless Username
       * @description Username for authentication
       */
      paperless_username?: string | null;
      /**
       * Paperless Password
       * @description Password for authentication
       */
      paperless_password?: string | null;
      /**
       * Fuzzy Match Threshold
       * @description Fuzzy matching threshold (50-100)
       */
      fuzzy_match_threshold?: number | null;
      /**
       * Max Ocr Length
       * @description Maximum OCR text length to store
       */
      max_ocr_length?: number | null;
      /**
       * Min Ocr Word Count
       * @description Minimum words in OCR to include in deduplication
       */
      min_ocr_word_count?: number | null;
      /**
       * Lsh Threshold
       * @description LSH similarity threshold
       */
      lsh_threshold?: number | null;
      /**
       * Enable Fuzzy Matching
       * @description Enable expensive fuzzy text matching
       */
      enable_fuzzy_matching?: boolean | null;
      /**
       * Fuzzy Match Sample Size
       * @description Characters to sample for fuzzy matching
       */
      fuzzy_match_sample_size?: number | null;
      /**
       * Confidence Weight Jaccard
       * @description Weight for Jaccard similarity (0-100)
       */
      confidence_weight_jaccard?: number | null;
      /**
       * Confidence Weight Fuzzy
       * @description Weight for fuzzy text matching (0-100)
       */
      confidence_weight_fuzzy?: number | null;
      /**
       * Confidence Weight Metadata
       * @description Weight for metadata similarity (0-100)
       */
      confidence_weight_metadata?: number | null;
      /**
       * Confidence Weight Filename
       * @description Weight for filename similarity (0-100, currently unused)
       */
      confidence_weight_filename?: number | null;
      /**
       * Openai Api Key
       * @description OpenAI API key for AI metadata extraction
       */
      openai_api_key?: string | null;
      /**
       * Openai Model
       * @description OpenAI model to use for metadata extraction (gpt-5.1, gpt-5-mini, gpt-5-nano)
       */
      openai_model?: string | null;
      /**
       * Openai Reasoning Effort
       * @description Reasoning depth to trade latency for quality (low, medium, high)
       */
      openai_reasoning_effort?: string | null;
      /**
       * Ai Max Input Chars
       * @description Maximum characters of document content sent to the LLM per document
       */
      ai_max_input_chars?: number | null;
    };
    /** ConfigValidationResponse */
    ConfigValidationResponse: {
      /** Valid */
      valid: boolean;
      /**
       * Errors
       * @default {}
       */
      errors: {
        [key: string]: string[];
      };
    };
    /** ConnectionTestResponse */
    ConnectionTestResponse: {
      /** Success */
      success: boolean;
      /** Message */
      message: string;
      /** Version */
      version?: string | null;
    };
    /** DocumentContentResponse */
    DocumentContentResponse: {
      /** Id */
      id: number;
      /** Document Id */
      document_id: number;
      /** Full Text */
      full_text: string;
      /** Content */
      content: string;
      /** Word Count */
      word_count?: number | null;
    };
    /** DocumentListResponse */
    DocumentListResponse: {
      /** Results */
      results: components['schemas']['DocumentResponse'][];
      /** Count */
      count: number;
      /** Next */
      next?: string | null;
      /** Previous */
      previous?: string | null;
      /** Next Cursor */
      next_cursor?: string | null;
      /** Prev Cursor */
      prev_cursor?: string | null;
      /**
       * Has Next
       * @default false
       */
      has_next: boolean;
      /**
       * Has Prev
       * @default false
       */
      has_prev: boolean;
    };
    /** DocumentResponse */
    DocumentResponse: {
      /** Id */
      id: number;
      /** Paperless Id */
      paperless_id: number;
      /** Title */
      title: string | null;
      /** Original File Size */
      original_file_size?: number | null;
      /** Archive File Size */
      archive_file_size?: number | null;
      /** Processing Status */
      processing_status: string;
      /**
       * Has Duplicates
       * @default false
       */
      has_duplicates: boolean;
      /** Created Date */
      created_date?: string | null;
      /** Last Processed */
      last_processed?: string | null;
    };
    /** DocumentStatsResponse */
    DocumentStatsResponse: {
      /** Total */
      total: number;
      /** Pending */
      pending: number;
      /** Processing */
      processing: number;
      /** Completed */
      completed: number;
      /** Errors */
      errors: number;
    };
    /** DocumentSync */
    DocumentSync: {
      /**
       * Force Refresh
       * @default false
       */
      force_refresh: boolean;
      /** Limit */
      limit?: number | null;
    };
    /** DuplicateGroupResponse */
    DuplicateGroupResponse: {
      /** Id */
      id: string;
      /** Confidence */
      confidence: number;
      /** Documents */
      documents: {
        [key: string]: unknown;
      }[];
      /** Reviewed */
      reviewed: boolean;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
      /** Confidence Breakdown */
      confidence_breakdown?: {
        [key: string]: unknown;
      } | null;
    };
    /** DuplicateGroupsListResponse */
    DuplicateGroupsListResponse: {
      /** Groups */
      groups: components['schemas']['DuplicateGroupResponse'][];
      /** Count */
      count: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** MarkReviewedRequest */
    MarkReviewedRequest: {
      /**
       * Reviewed
       * @default true
       */
      reviewed: boolean;
      /**
       * Resolved
       * @default false
       */
      resolved: boolean;
    };
    /**
     * OperationStatus
     * @enum {string}
     */
    OperationStatus:
      | 'pending'
      | 'in_progress'
      | 'completed'
      | 'failed'
      | 'partially_completed';
    /**
     * OperationType
     * @enum {string}
     */
    OperationType:
      | 'mark_for_deletion'
      | 'delete'
      | 'tag'
      | 'untag'
      | 'update_metadata'
      | 'merge_documents'
      | 'mark_reviewed'
      | 'resolve_duplicates';
    /** ProcessingHistoryEntry */
    ProcessingHistoryEntry: {
      /** Id */
      id: string;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
      /** Status */
      status: string;
      /**
       * Documents Processed
       * @default 0
       */
      documents_processed: number;
      /**
       * Groups Found
       * @default 0
       */
      groups_found: number;
      /** Error */
      error?: string | null;
    };
    /** ProcessingHistoryResponse */
    ProcessingHistoryResponse: {
      /** Runs */
      runs: components['schemas']['ProcessingHistoryEntry'][];
    };
    /** SystemHealth */
    SystemHealth: {
      /** Overall Status */
      overall_status: string;
      database: components['schemas']['ComponentHealth'];
      paperless_api: components['schemas']['ComponentHealth'];
      celery_worker?: components['schemas']['ComponentHealth'] | null;
      redis?: components['schemas']['ComponentHealth'] | null;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Uptime Seconds */
      uptime_seconds?: number | null;
    };
    /**
     * TaskUpdate
     * @description Task update payload from workers
     */
    TaskUpdate: {
      /** Task Id */
      task_id: string;
      /** Status */
      status: string;
      /** Step */
      step?: string | null;
      /** Progress */
      progress?: number | null;
      /** Total */
      total?: number | null;
      /** Result */
      result?: {
        [key: string]: unknown;
      } | null;
      /** Error */
      error?: string | null;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
      /** Task Type */
      task_type?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_documents_api_v1_documents__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        /** @description Cursor for pagination */
        cursor?: string | null;
        /** @description Field to order by */
        order_by?: string;
        /** @description Order descending */
        order_desc?: boolean;
        /** @description Search document titles */
        search?: string | null;
        /** @description Filter by processing status */
        processing_status?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_document_stats_api_v1_documents_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentStatsResponse'];
        };
      };
    };
  };
  get_document_statistics_api_v1_documents_statistics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_document_api_v1_documents__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_document_content_api_v1_documents__document_id__content_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentContentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_document_preview_api_v1_documents__document_id__preview_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_document_duplicates_api_v1_documents__document_id__duplicates_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  sync_documents_api_v1_documents_sync_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DocumentSync'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_statistics_api_v1_documents_statistics_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_sync_status_api_v1_documents_sync_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_duplicate_groups_api_v1_duplicates_groups_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        min_confidence?: number;
        reviewed?: boolean | null;
        resolved?: boolean | null;
        sort_by?: string;
        sort_order?: string;
        use_jaccard?: boolean;
        use_fuzzy?: boolean;
        use_metadata?: boolean;
        min_fuzzy_ratio?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DuplicateGroupsListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_duplicate_group_api_v1_duplicates_groups__group_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        group_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DuplicateGroupResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_duplicate_group_api_v1_duplicates_groups__group_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        group_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mark_group_reviewed_api_v1_duplicates_groups__group_id__review_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        group_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MarkReviewedRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_duplicate_statistics_api_v1_duplicates_statistics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  start_analysis_api_v1_processing_analyze_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AnalyzeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_processing_status_api_v1_processing_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  cancel_processing_api_v1_processing_cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  clear_cache_api_v1_processing_clear_cache_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  broadcast_task_update_api_v1_processing_internal_broadcast_task_update_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_processing_history_api_v1_processing_history_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProcessingHistoryResponse'];
        };
      };
    };
  };
  cleanup_duplicate_data_api_v1_processing_cleanup_duplicates_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  list_ai_jobs_api_v1_ai_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AIJobSummary'][];
        };
      };
    };
  };
  create_ai_job_api_v1_ai_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AIJobRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AIJobSummary'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_ai_job_api_v1_ai_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AIJobSummary'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_ai_results_api_v1_ai_jobs__job_id__results_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        job_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  apply_ai_results_api_v1_ai_jobs__job_id__apply_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ApplyJobRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  check_openai_health_api_v1_ai_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AIHealthResponse'];
        };
      };
    };
  };
  get_config_api_v1_config__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigResponse'];
        };
      };
    };
  };
  update_config_api_v1_config__put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfigUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_config_defaults_api_v1_config_defaults_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigResponse'];
        };
      };
    };
  };
  validate_config_api_v1_config_validate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigValidationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  test_paperless_connection_api_v1_config_test_connection_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['ConfigUpdate'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConnectionTestResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reset_config_api_v1_config_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigResponse'];
        };
      };
    };
  };
  execute_batch_operation_endpoint_api_v1_batch_execute_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchOperationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchOperationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_operation_status_api_v1_batch_status__operation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchOperationProgress'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  bulk_get_documents_api_v1_batch_documents_bulk_get_post: {
    parameters: {
      query?: {
        include_content?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': number[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  bulk_update_metadata_api_v1_batch_documents_bulk_metadata_update_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Body_bulk_update_metadata_api_v1_batch_documents_bulk_metadata_update_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_operations_api_v1_batch_operations_get: {
    parameters: {
      query?: {
        status?: components['schemas']['OperationStatus'] | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchOperationProgress'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cancel_operation_api_v1_batch_cancel__operation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  bulk_resolve_duplicates_api_v1_batch_duplicates_bulk_resolve_post: {
    parameters: {
      query?: {
        keep_primary?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': string[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  bulk_review_duplicates_api_v1_batch_duplicates_bulk_review_post: {
    parameters: {
      query?: {
        reviewed?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': string[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  broadcast_task_update_api_v1_internal_broadcast_task_update_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_system_health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SystemHealth'];
        };
      };
    };
  };
  get_quick_health_api_v1_health_quick_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_health_metrics_api_v1_health_metrics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  api_root_api_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  api_health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
