name: Setup Node.js with pnpm
description: Setup pnpm, Node.js, and restore cached node_modules

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: 24

    - name: Restore node_modules
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
